name: stable
on:
  push:
    branches:
      main
  schedule:
    - cron: 0 2 * * *
jobs:
  nimstable-ltsc2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: |
          $nim_version = ((Invoke-RestMethod -Uri https://api.github.com/repos/nim-lang/Nim/tags).Name | Select-Object -first 1).Trim("v")
          docker build . --file Dockerfile --tag nimstable-ltsc2022 --build-arg nim_version=$nim_version --build-arg mingit_full_version=$mingit_full_version --build-arg mingit_short_version=$mingit_short_version
      - name: log into github registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: tag and push image
        run: |
          docker tag nimstable-ltsc2022 docker.pkg.github.com/sirredbeard/nim-windows-container/nimstable-ltsc2022:latest
          docker push docker.pkg.github.com/${{ github.repository }}/nimstable-ltsc2022
